#!/usr/bin/env bash

#  Copyright 2019 Giacomo Ferretti
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Name of the patch
P_NAME="AppName"
P_VERSION="1.0.0"

TARGET_FILE="${PATCH_FOLDER}/res/values/strings.xml"

NEW_NAME="McMod"

# Main function
function patch {
    sed -i "s/\"McDonald's\"/\"${NEW_NAME}\"/g" "${TARGET_FILE}"
}

info "Applying ${P_NAME} [${P_VERSION}]..."
patch
