#!/usr/bin/env bash

#  Copyright 2019 Giacomo Ferretti
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Name of the patch
P_NAME="MainUrl_v2"
P_VERSION="2.1.0"

PATCH_STRING="const-string v0, \"${TARGET_URL}%s-%s\"\nconst/4 v1, 0x2\nnew-array v1, v1, [Ljava/lang/Object;\nconst/4 v2, 0x0\naput-object p0, v1, v2\nconst/4 v2, 0x1\naput-object p1, v1, v2\ninvoke-static {v0, v1}, Ljava/lang/String;->format(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;\nmove-result-object v0\nreturn-object v0"

# Main function
function patch {
    grep -lR "const-string v0, \"di\"" "${PATCH_FOLDER}" | while read -r line; do
        verbose " ↪ Patching ${line}..."
        sed -i "" "/const-string v0, \"https:\/\/\"/,/return-object v0/c${PATCH_STRING//\//\\/}" "${line}"
    done
}

info "Applying ${P_NAME} [${P_VERSION}]..."
patch
