#!/usr/bin/env bash

#  Copyright 2019 Giacomo Ferretti
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Name of the patch
P_NAME="PackageRenamer"
P_VERSION="1.1.0"

NEW_PACKAGE="com.mcdonalds.mobileappmod"

# Main function
function patch {
    # find "${PATCH_FOLDER}" -printf '%p' -type f ! -path '*/assets/*' ! -path '*/apktool.yml' -exec sed -i "s/com.mcdonalds.mobileapp/${NEW_PACKAGE}/g" {} +
    grep -lR --exclude="apktool.yml" --exclude-dir="assets" "${PACKAGE_NAME//./\\.}" "${PATCH_FOLDER}" | while read -r line; do
        sed -i "" "s/${PACKAGE_NAME}/${NEW_PACKAGE}/g" "${line}"
    done
}

info "Applying ${P_NAME} [${P_VERSION}]..."
patch
