#!/usr/bin/env bash

#  Copyright 2019 Giacomo Ferretti
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Name of the patch
P_NAME="SafetyNetRemover"
P_VERSION="2.1.0"

CUSTOM_SNET_TOKEN="McMod"

# Main function
function patch {
    while read -r line; do
        EXTRACTED=$(perl -ne 'print "$1" if /check-cast v0, (.*)/' ${line})
    done <<< "$(grep -lR "check-cast p1, Lcom/google/android/gms/safetynet/SafetyNetApi\$AttestationResponse;" "${PATCH_FOLDER}")"

    PATCH_STRING="if-eqz p1, :cond_0\ncheck-cast p1, ${EXTRACTED}\nconst-string v1, \"${CUSTOM_SNET_TOKEN}\"\ninvoke-virtual {p1, v1}, ${EXTRACTED}->a(Ljava/lang/Object;)V\nreturn-void"

    grep -lR "invoke-virtual {v0, v1, v2}, Lcom/google/android/gms/safetynet/SafetyNetClient;->a(\[BLjava/lang/String;)Lcom/google/android/gms/tasks/Task;" "${PATCH_FOLDER}" | while read -r line; do
        verbose " ↪ Patching ${line}..."
        if [[ "$(uname)" == "Darwin" ]]; then
            sed -i '' "/if-eqz p1, :cond_0/,/return-void/c\ 
            ${PATCH_STRING//\//\\/}" "${line}"
        elif [[ "$(uname -s | cut -c -5)" == "Linux" ]]; then
            sed -i "/if-eqz p1, :cond_0/,/return-void/c${PATCH_STRING//\//\\/}" "${line}"
        fi
    done
}

info "Applying ${P_NAME} [${P_VERSION}]..."
patch
