#!/usr/bin/env bash

#  Copyright 2019 Giacomo Ferretti
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Name of the patch
P_NAME="VersionName"
P_VERSION="1.1.0"

TARGET_FILE_1="${PATCH_FOLDER}/AndroidManifest.xml"
TARGET_FILE_2="${PATCH_FOLDER}/apktool.yml"

FORMAT="${VERSION_NAME}_mod_${PATCH_VERSION}"

# Main function
function patch {
    verbose " ↪ Patching ${TARGET_FILE_1}..."
    _sed -E "s/platformBuildVersionName=\"(.*)\"/platformBuildVersionName=\"${FORMAT}\"/g" "${TARGET_FILE_1}"

    verbose " ↪ Patching ${TARGET_FILE_2}..."
    _sed -E "s/versionName: (.*)/versionName: ${FORMAT}/g" "${TARGET_FILE_2}"
}

info "Applying ${P_NAME} [${P_VERSION}]..."
patch
