#!/usr/bin/env bash

#  Copyright 2019 Giacomo Ferretti
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Name of the patch
P_NAME="SafetyNetRemover"
P_VERSION="1.0.0"

CUR_FOLDER="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

TARGET_VERSION="3807"
TARGET_FILE="${PATCH_FOLDER}/smali_classes2/com/Jma.smali"
CUSTOM_SNET_TOKEN="McMod"

# Main function
function patch {
	if [[ "${VERSION_CODE}" == "${TARGET_VERSION}" ]]; then
		info "\tPatch compatible with ${VERSION_CODE}!"
		cp -f "${CUR_FOLDER}/Jma.smali" "${TARGET_FILE}"
	    sed -i "s/\"REPLACE\"/\"${CUSTOM_SNET_TOKEN}\"/g" "${TARGET_FILE}"
	else
		info "\tPatch incompatible with ${VERSION_CODE}!"
	fi
}

info "Applying ${P_NAME} [${P_VERSION}]..."
patch
